http {
  server {
    listen localhost:8080;
    root /data/www;
    index index.html;
    client_max_body_size 1000;  # 1KB limit

    # error_page 400 /error_pages/error400.html;
    # error_page 403 /error_pages/error403.html;
    error_page 404 /error_pages/error404.html;
    # error_page 405 /error_pages/error405.html;
    # error_page 413 /error_pages/error413.html;
    # error_page 500 /error_pages/error500.html;
    # error_page 501 /error_pages/error501.html;
    # error_page 504 /error_pages/error504.html;

    location / {
      root /data/www;
      index index.html;
      methods GET POST;
    }

    location /images {
      root data/www/images;
	  autoindex on;
      methods GET;
    }

    location /static/ {
      root /data/www/static;
      methods GET;
    }

    location /upload {
      root /data/www/upload;
	  autoindex on;
	  methods POST DELETE GET;
	  upload_dir data/www/upload;
    }

	location /cgi-bin {
        cgi_extension .py /usr/bin/python3;
        root /data/www;
		methods POST GET;
    }

	location /old {
		return 301 /new;
	}

	location /new {
		root /data/www/new;
		index index.html;
	}
  }
    server {
		listen localhost:8085;
		root /data/www;
		index index.html;
		client_max_body_size 1000;  # 1KB limit

		error_page 400 /error_pages/error400.html;
		error_page 403 /error_pages/error403.html;
		error_page 404 /error_pages/error404.html;
		error_page 405 /error_pages/error405.html;
		error_page 413 /error_pages/error413.html;
		error_page 500 /error_pages/error500.html;

		location / {
			root /data/www;
			index index.html;
			methods GET POST DELETE;
		}

		location /images {
			root data/www/images;
			methods GET;
		}

		location /static/ {
			root /data/www/static;
			methods GET;
		}

		location /old {
			return 301 /new;
		}

		location /upload {
			root /data/www/upload;
			index upload.html;
			autoindex on;
			methods POST DELETE;
			upload_dir data/www/upload;
		}
		
		location /cgi-bin {
			cgi_extension .py /usr/bin/python3;
			root /data/www;
			methods POST GET;
		}

		location /new_files {
			root /data/www/new_files;
			methods POST DELETE;
			upload_dir data/www/new_files;
		}
  	}
}
